"""add chat visitor avatar

Revision ID: 07dcdfcce02c
Revises: 269c87f9893a
Create Date: 2026-02-13 16:36:56.943635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '07dcdfcce02c'
down_revision: Union[str, Sequence[str], None] = '269c87f9893a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_visitors', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_visitors', 'avatar_url')
    # ### end Alembic commands ###
