"""add chat conversation read state

Revision ID: 0e25f0cd9ae0
Revises: ff6a7b8c9d0e
Create Date: 2026-02-13 15:27:41.778501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0e25f0cd9ae0'
down_revision: Union[str, Sequence[str], None] = 'ff6a7b8c9d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('last_read_at', sa.DateTime(), nullable=True))
    op.add_column(
        'chat_conversations',
        sa.Column('unread_count', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_conversations', 'unread_count')
    op.drop_column('chat_conversations', 'last_read_at')
    # ### end Alembic commands ###
