"""add chat visitor profile fields

Revision ID: 269c87f9893a
Revises: 0e25f0cd9ae0
Create Date: 2026-02-13 15:39:30.621295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '269c87f9893a'
down_revision: Union[str, Sequence[str], None] = '0e25f0cd9ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_visitors', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('chat_visitors', sa.Column('referrer', sa.String(), nullable=True))
    op.add_column('chat_visitors', sa.Column('utm_source', sa.String(), nullable=True))
    op.add_column('chat_visitors', sa.Column('utm_medium', sa.String(), nullable=True))
    op.add_column('chat_visitors', sa.Column('utm_campaign', sa.String(), nullable=True))
    op.add_column('chat_visitors', sa.Column('ip', sa.String(), nullable=True))
    op.add_column('chat_visitors', sa.Column('country', sa.String(), nullable=True))
    op.add_column('chat_visitors', sa.Column('city', sa.String(), nullable=True))
    op.add_column('chat_visitors', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('chat_visitors', sa.Column('language', sa.String(), nullable=True))
    op.add_column('chat_visitors', sa.Column('browser', sa.String(), nullable=True))
    op.add_column('chat_visitors', sa.Column('os', sa.String(), nullable=True))
    op.add_column('chat_visitors', sa.Column('device', sa.String(), nullable=True))
    op.add_column('chat_visitors', sa.Column('last_page', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_visitors', 'last_page')
    op.drop_column('chat_visitors', 'device')
    op.drop_column('chat_visitors', 'os')
    op.drop_column('chat_visitors', 'browser')
    op.drop_column('chat_visitors', 'language')
    op.drop_column('chat_visitors', 'timezone')
    op.drop_column('chat_visitors', 'city')
    op.drop_column('chat_visitors', 'country')
    op.drop_column('chat_visitors', 'ip')
    op.drop_column('chat_visitors', 'utm_campaign')
    op.drop_column('chat_visitors', 'utm_medium')
    op.drop_column('chat_visitors', 'utm_source')
    op.drop_column('chat_visitors', 'referrer')
    op.drop_column('chat_visitors', 'phone')
    # ### end Alembic commands ###
