"""add profile_image to users

Revision ID: f7047335459d
Revises: 7f1d4e2b9c1a
Create Date: 2026-01-24 10:01:19.078603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7047335459d'
down_revision: Union[str, Sequence[str], None] = '7f1d4e2b9c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_billing_id'), 'users', ['billing_id'], unique=False)
    op.create_index(op.f('ix_users_plan_id'), 'users', ['plan_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_status_id'), 'users', ['status_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status_id'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_plan_id'), table_name='users')
    op.drop_index(op.f('ix_users_billing_id'), table_name='users')
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
